[project]
name = "t11"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7.17"
dependencies = [
    "fastapi>=0.103.2",
]

[tool.uv.workspace]
members = [
    "t111",
]
